<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V6;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * Order item details from an order.
 * @method static OrderOrderItem fromArray(array $data)
 */
final class OrderOrderItem extends Model
{
    /**
     * The id for the order item. One order can have multiple order items,
     * but the list can only take one item.
     * @var string
     */
    protected $orderItemId = '';

    /**
     * Indicates whether the order was cancelled on request of the customer
     * before the retailer has shipped it.
     * @var bool
     */
    protected $cancellationRequest = false;

    /** @var OrderFulfilment */
    protected $fulfilment;

    /** @var OrderOffer */
    protected $offer;

    /** @var OrderProduct */
    protected $product;

    /**
     * Amount of ordered products for this order item id.
     * @var int
     */
    protected $quantity = 0;

    /**
     * Amount of shipped products for this order item id.
     * @var int
     */
    protected $quantityShipped = 0;

    /**
     * Amount of cancelled products for this order item id.
     * @var int
     */
    protected $quantityCancelled = 0;

    /**
     * The selling price to the customer of a single unit including VAT.
     * @var float
     */
    protected $unitPrice = 0;

    /**
     * The commission for all quantities of this order item.
     * @var float
     */
    protected $commission = 0;

    /** @var AdditionalService[] */
    protected $additionalServices = [];

    public function setOrderItemId(?string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): ?string
    {
        return $this->orderItemId;
    }

    public function setCancellationRequest(?bool $cancellationRequest): self
    {
        $this->cancellationRequest = $cancellationRequest;
        return $this;
    }

    public function getCancellationRequest(): ?bool
    {
        return $this->cancellationRequest;
    }

    public function setFulfilment(?OrderFulfilment $fulfilment): self
    {
        $this->fulfilment = $fulfilment;
        return $this;
    }

    public function getFulfilment(): ?OrderFulfilment
    {
        return $this->fulfilment;
    }

    public function setOffer(?OrderOffer $offer): self
    {
        $this->offer = $offer;
        return $this;
    }

    public function getOffer(): ?OrderOffer
    {
        return $this->offer;
    }

    public function setProduct(?OrderProduct $product): self
    {
        $this->product = $product;
        return $this;
    }

    public function getProduct(): ?OrderProduct
    {
        return $this->product;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    public function setQuantityShipped(?int $quantityShipped): self
    {
        $this->quantityShipped = $quantityShipped;
        return $this;
    }

    public function getQuantityShipped(): ?int
    {
        return $this->quantityShipped;
    }

    public function setQuantityCancelled(?int $quantityCancelled): self
    {
        $this->quantityCancelled = $quantityCancelled;
        return $this;
    }

    public function getQuantityCancelled(): ?int
    {
        return $this->quantityCancelled;
    }

    public function setUnitPrice(?float $unitPrice): self
    {
        $this->unitPrice = $unitPrice;
        return $this;
    }

    public function getUnitPrice(): ?float
    {
        return $this->unitPrice;
    }

    public function setCommission(?float $commission): self
    {
        $this->commission = $commission;
        return $this;
    }

    public function getCommission(): ?float
    {
        return $this->commission;
    }

    public function setAdditionalServices(?AdditionalService ...$additionalServices): self
    {
        $this->additionalServices = $additionalServices;
        return $this;
    }

    public function getAdditionalServices(): ?array
    {
        return $this->additionalServices;
    }
}
