<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V6;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static PerformanceIndicators fromArray(array $data)
 */
final class PerformanceIndicators extends Model
{
    /** @var PerformanceIndicator[] */
    protected $performanceIndicators = [];

    public function setPerformanceIndicators(PerformanceIndicator ...$performanceIndicators): self
    {
        $this->performanceIndicators = $performanceIndicators;
        return $this;
    }

    public function getPerformanceIndicators(): array
    {
        return $this->performanceIndicators;
    }
}
