<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V7\Advertiser\CreateKeywordRequest\MatchType;

/**
 * @method static CreateKeywordRequest fromArray(array $data)
 */
final class CreateKeywordRequest extends Model
{
    /** The identifier of the parent ad group. */
    protected string $adGroupId = '';

    /**
     * The text or phrase used in the keyword that caused the ad to be
     * displayed to the user.
     */
    protected string $keywordText = '';

    /** The match type that relates the keyword and the search term. */
    protected MatchType $matchType;

    /** The bid price. The price should always have two decimals of precision. */
    protected ?float $bid = 0;

    public function setAdGroupId(string $adGroupId): self
    {
        $this->adGroupId = $adGroupId;
        return $this;
    }

    public function getAdGroupId(): string
    {
        return $this->adGroupId;
    }

    public function setKeywordText(string $keywordText): self
    {
        $this->keywordText = $keywordText;
        return $this;
    }

    public function getKeywordText(): string
    {
        return $this->keywordText;
    }

    public function setMatchType(MatchType $matchType): self
    {
        $this->matchType = $matchType;
        return $this;
    }

    public function getMatchType(): MatchType
    {
        return $this->matchType;
    }

    public function setBid(?float $bid): self
    {
        $this->bid = $bid;
        return $this;
    }

    public function getBid(): ?float
    {
        return $this->bid;
    }
}
