<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static KeywordsResponse fromArray(array $data)
 */
final class KeywordsResponse extends Model
{
    /** @var Keyword[] */
    protected array $keywords = [];

    public function setKeywords(Keyword ...$keywords): self
    {
        $this->keywords = $keywords;
        return $this;
    }

    public function getKeywords(): array
    {
        return $this->keywords;
    }
}
