<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static CreatePickupAppointment fromArray(array $data)
 */
final class CreatePickupAppointment extends Model
{
    protected CreateAddress $address;
    protected CreatePickupTimeSlot $pickupTimeSlot;

    /** A comment to the transporter regarding the pickup appointment. */
    protected ?string $commentToTransporter = '';

    public function setAddress(CreateAddress $address): self
    {
        $this->address = $address;
        return $this;
    }

    public function getAddress(): CreateAddress
    {
        return $this->address;
    }

    public function setPickupTimeSlot(CreatePickupTimeSlot $pickupTimeSlot): self
    {
        $this->pickupTimeSlot = $pickupTimeSlot;
        return $this;
    }

    public function getPickupTimeSlot(): CreatePickupTimeSlot
    {
        return $this->pickupTimeSlot;
    }

    public function setCommentToTransporter(?string $commentToTransporter): self
    {
        $this->commentToTransporter = $commentToTransporter;
        return $this;
    }

    public function getCommentToTransporter(): ?string
    {
        return $this->commentToTransporter;
    }
}
