<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static DeliveryDatesResponse fromArray(array $data)
 */
final class DeliveryDatesResponse extends Model
{
    /**
     * Allowed delivery dates for shipments to the bol.com warehouse in ISO
     * 8601 format.
     */
    protected ?array $deliveryDates = [];

    public function setDeliveryDates(?array $deliveryDates): self
    {
        $this->deliveryDates = $deliveryDates;
        return $this;
    }

    public function getDeliveryDates(): ?array
    {
        return $this->deliveryDates;
    }
}
