<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V7\Retailer\Norm\Condition;

/**
 * @method static Norm fromArray(array $data)
 */
final class Norm extends Model
{
    /** Condition norm for this indicator. */
    protected Condition $condition;

    /** Service norm for this indicator. */
    protected float $value = 0;

    public function setCondition(Condition $condition): self
    {
        $this->condition = $condition;
        return $this;
    }

    public function getCondition(): Condition
    {
        return $this->condition;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;
        return $this;
    }

    public function getValue(): float
    {
        return $this->value;
    }
}
