<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * A single product.
 * @method static Product fromArray(array $data)
 */
final class Product extends Model
{
    /** The EAN number associated with this product. */
    protected string $ean = '';

    /** @var RelevanceScore[] */
    protected array $relevanceScores = [];

    /**
     * The maximum price a product can have in order to be part of the
     * promotion.
     */
    protected float $maximumPrice = 0;

    public function setEan(string $ean): self
    {
        $this->ean = $ean;
        return $this;
    }

    public function getEan(): string
    {
        return $this->ean;
    }

    public function setRelevanceScores(?RelevanceScore ...$relevanceScores): self
    {
        $this->relevanceScores = $relevanceScores;
        return $this;
    }

    public function getRelevanceScores(): ?array
    {
        return $this->relevanceScores;
    }

    public function setMaximumPrice(?float $maximumPrice): self
    {
        $this->maximumPrice = $maximumPrice;
        return $this;
    }

    public function getMaximumPrice(): ?float
    {
        return $this->maximumPrice;
    }
}
