<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V7\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * An order item.
 * @method static ReducedOrderItem fromArray(array $data)
 */
final class ReducedOrderItem extends Model
{
    /**
     * The id for the order item. One order can have multiple order items,
     * but the list can only take one item.
     */
    protected string $orderItemId = '';

    /** The EAN number associated with this product. */
    protected string $ean = '';

    /** Amount of ordered products for this order item id. */
    protected int $quantity = 0;

    /** Amount of shipped products for this order item id. */
    protected int $quantityShipped = 0;

    /** Amount of cancelled products for this order item id. */
    protected int $quantityCancelled = 0;

    public function setOrderItemId(string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): string
    {
        return $this->orderItemId;
    }

    public function setEan(string $ean): self
    {
        $this->ean = $ean;
        return $this;
    }

    public function getEan(): string
    {
        return $this->ean;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getQuantity(): int
    {
        return $this->quantity;
    }

    public function setQuantityShipped(int $quantityShipped): self
    {
        $this->quantityShipped = $quantityShipped;
        return $this;
    }

    public function getQuantityShipped(): int
    {
        return $this->quantityShipped;
    }

    public function setQuantityCancelled(int $quantityCancelled): self
    {
        $this->quantityCancelled = $quantityCancelled;
        return $this;
    }

    public function getQuantityCancelled(): int
    {
        return $this->quantityCancelled;
    }
}
