<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V5\PerformanceIndicator;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class Type extends Enum
{
    protected const MAX_ITEMS = 1;
    public const PERCENTAGE = 'PERCENTAGE';
    public const AVERAGE = 'AVERAGE';

    protected $allowedValues = ['PERCENTAGE', 'AVERAGE'];

    public static function percentage(): self
    {
        return (new static())->set(static::PERCENTAGE);
    }

    public static function average(): self
    {
        return (new static())->set(static::AVERAGE);
    }
}
