<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V7\ReducedPromotion;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class PromotionType extends Enum
{
    protected const MAX_ITEMS = 1;
    public const AWARENESS = 'AWARENESS';
    public const PRICE_OFF = 'PRICE_OFF';

    protected $allowedValues = ['AWARENESS', 'PRICE_OFF'];

    public static function awareness(): self
    {
        return (new static())->set(static::AWARENESS);
    }

    public function isAwareness(): bool
    {
        return $this->is(static::AWARENESS);
    }

    public static function priceOff(): self
    {
        return (new static())->set(static::PRICE_OFF);
    }

    public function isPriceOff(): bool
    {
        return $this->is(static::PRICE_OFF);
    }
}
