<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V5\OrderFulfilment;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class TimeFrameType extends Enum
{
    protected const MAX_ITEMS = 1;
    public const REGULAR = 'REGULAR';
    public const EVENING = 'EVENING';
    public const APPOINTMENT = 'APPOINTMENT';
    public const SAMEDAY = 'SAMEDAY';
    public const SUNDAY = 'SUNDAY';

    protected $allowedValues = ['REGULAR', 'EVENING', 'APPOINTMENT', 'SAMEDAY', 'SUNDAY'];

    public static function regular(): self
    {
        return (new static())->set(static::REGULAR);
    }

    public static function evening(): self
    {
        return (new static())->set(static::EVENING);
    }

    public static function appointment(): self
    {
        return (new static())->set(static::APPOINTMENT);
    }

    public static function sameday(): self
    {
        return (new static())->set(static::SAMEDAY);
    }

    public static function sunday(): self
    {
        return (new static())->set(static::SUNDAY);
    }
}
