<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Endpoints\V9\Retailer\Products;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class AcceptLanguage extends Enum
{
    public const NL = 'nl';
    public const NL_BE = 'nl-BE';
    public const FR_BE = 'fr-BE';

    protected array $allowedValues = ['nl', 'nl-BE', 'fr-BE'];

    public static function nl(): self
    {
        return (new static())->set(static::NL);
    }

    public function isNl(): bool
    {
        return $this->is(static::NL);
    }

    public static function nlBe(): self
    {
        return (new static())->set(static::NL_BE);
    }

    public function isNlBe(): bool
    {
        return $this->is(static::NL_BE);
    }

    public static function frBe(): self
    {
        return (new static())->set(static::FR_BE);
    }

    public function isFrBe(): bool
    {
        return $this->is(static::FR_BE);
    }
}
