<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static BulkCommissionQuery fromArray(array $data)
 */
final class BulkCommissionQuery extends Model
{
    /**
     * The EAN number associated with this product.
     * @var string
     */
    protected $ean = '';

    /**
     * The condition of the offer.
     * @var string
     */
    protected $condition = '';

    /**
     * The price of the product with a period as a decimal separator. The
     * price should always have two decimals precision.
     * @var float
     */
    protected $unitPrice = 0;

    public function setEan(string $ean): self
    {
        $this->ean = $ean;
        return $this;
    }

    public function getEan(): string
    {
        return $this->ean;
    }

    public function setCondition(?string $condition): self
    {
        $this->condition = $condition;
        return $this;
    }

    public function getCondition(): ?string
    {
        return $this->condition;
    }

    public function setUnitPrice(float $unitPrice): self
    {
        $this->unitPrice = $unitPrice;
        return $this;
    }

    public function getUnitPrice(): float
    {
        return $this->unitPrice;
    }
}
