<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static CreateReturnRequest fromArray(array $data)
 */
final class CreateReturnRequest extends Model
{
    /**
     * The id for the order item (1 order can have multiple order items).
     * @var string
     */
    protected $orderItemId = '';

    /**
     * The quantity of items returned.
     * @var int
     */
    protected $quantityReturned = 0;

    /**
     * The handling result requested by the retailer.
     * @var string
     */
    protected $handlingResult = '';

    public function setOrderItemId(string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): string
    {
        return $this->orderItemId;
    }

    public function setQuantityReturned(int $quantityReturned): self
    {
        $this->quantityReturned = $quantityReturned;
        return $this;
    }

    public function getQuantityReturned(): int
    {
        return $this->quantityReturned;
    }

    public function setHandlingResult(string $handlingResult): self
    {
        $this->handlingResult = $handlingResult;
        return $this;
    }

    public function getHandlingResult(): string
    {
        return $this->handlingResult;
    }
}
