<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static Details fromArray(array $data)
 */
final class Details extends Model
{
    /** The period for which the performance is measured. */
    protected $period;

    /**
     * The score for this measurement. In case there are no scores for an
     * indicator, this element is omitted from the response.
     */
    protected $score;

    /** Service norm for this indicator. */
    protected $norm;

    public function setPeriod($period): self
    {
        $this->period = $period;
        return $this;
    }

    public function getPeriod()
    {
        return $this->period;
    }

    public function setScore($score): self
    {
        $this->score = $score;
        return $this;
    }

    public function getScore()
    {
        return $this->score;
    }

    public function setNorm($norm): self
    {
        $this->norm = $norm;
        return $this;
    }

    public function getNorm()
    {
        return $this->norm;
    }
}
