<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static LabelPrice fromArray(array $data)
 */
final class LabelPrice extends Model
{
    /**
     * The price that is charged for this delivery option, excluding VAT.
     * @var float
     */
    protected $totalPrice;

    public function setTotalPrice(?float $totalPrice): self
    {
        $this->totalPrice = $totalPrice;
        return $this;
    }

    public function getTotalPrice(): ?float
    {
        return $this->totalPrice;
    }
}
