<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static Norm fromArray(array $data)
 */
final class Norm extends Model
{
    /**
     * Condition norm for this indicator.
     * @var string
     */
    protected $condition;

    /**
     * Service norm for this indicator.
     * @var float
     */
    protected $value;

    public function setCondition(string $condition): self
    {
        $this->condition = $condition;
        return $this;
    }

    public function getCondition(): string
    {
        return $this->condition;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;
        return $this;
    }

    public function getValue(): float
    {
        return $this->value;
    }
}
