<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static OfferInsightsCountry fromArray(array $data)
 */
final class OfferInsightsCountry extends Model
{
    /**
     * Countries in which this offer is currently on sale in the webshop, in
     * ISO-3166-1 format.
     * @var string
     */
    protected $countryCode;

    /**
     * The total value of offer insight.
     * @var float
     */
    protected $value;

    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;
        return $this;
    }

    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;
        return $this;
    }

    public function getValue(): float
    {
        return $this->value;
    }
}
