<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static OfferInsightsPeriod fromArray(array $data)
 */
final class OfferInsightsPeriod extends Model
{
    /**
     * Day of the month.
     * @var int
     */
    protected $day;

    /**
     * Week of the year.
     * @var int
     */
    protected $week;

    /**
     * Month of the year.
     * @var int
     */
    protected $month;

    /**
     * Year.
     * @var int
     */
    protected $year;

    public function setDay(?int $day): self
    {
        $this->day = $day;
        return $this;
    }

    public function getDay(): ?int
    {
        return $this->day;
    }

    public function setWeek(?int $week): self
    {
        $this->week = $week;
        return $this;
    }

    public function getWeek(): ?int
    {
        return $this->week;
    }

    public function setMonth(?int $month): self
    {
        $this->month = $month;
        return $this;
    }

    public function getMonth(): ?int
    {
        return $this->month;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;
        return $this;
    }

    public function getYear(): int
    {
        return $this->year;
    }
}
