<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V5\OrderItemCancellation\ReasonCode;

/**
 * @method static OrderItemCancellation fromArray(array $data)
 */
final class OrderItemCancellation extends Model
{
    /**
     * The id for the order item (1 order can have multiple order items).
     * @var string
     */
    protected $orderItemId = '';

    /**
     * The code representing the reason for cancellation of this item.
     * @var ReasonCode
     */
    protected $reasonCode;

    public function setOrderItemId(string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): string
    {
        return $this->orderItemId;
    }

    public function setReasonCode(ReasonCode $reasonCode): self
    {
        $this->reasonCode = $reasonCode;
        return $this;
    }

    public function getReasonCode(): ReasonCode
    {
        return $this->reasonCode;
    }
}
