<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static ProcessStatus fromArray(array $data)
 */
final class ProcessStatus extends Model
{
    /**
     * The process status id.
     * @var string
     */
    protected $processStatusId = '';

    /**
     * The id of the object being processed. E.g. in case of a shipment
     * process id, you will receive the id of the order item being processed.
     * @var string
     */
    protected $entityId = '';

    /**
     * Name of the requested action that is being processed.
     * @var string
     */
    protected $eventType = '';

    /**
     * Describes the action that is being processed.
     * @var string
     */
    protected $description = '';

    /**
     * Status of the action being processed.
     * @var string
     */
    protected $status = '';

    /**
     * Shows error message if applicable.
     * @var string
     */
    protected $errorMessage = '';

    /**
     * Time of creation of the response.
     * @var string
     */
    protected $createTimestamp = '';

    /**
     * Lists available actions applicable to this endpoint.
     * @var Link[]
     */
    protected $links = [];

    public function setProcessStatusId(?string $processStatusId): self
    {
        $this->processStatusId = $processStatusId;
        return $this;
    }

    public function getProcessStatusId(): ?string
    {
        return $this->processStatusId;
    }

    public function setEntityId(?string $entityId): self
    {
        $this->entityId = $entityId;
        return $this;
    }

    public function getEntityId(): ?string
    {
        return $this->entityId;
    }

    public function setEventType(string $eventType): self
    {
        $this->eventType = $eventType;
        return $this;
    }

    public function getEventType(): string
    {
        return $this->eventType;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;
        return $this;
    }

    public function getDescription(): string
    {
        return $this->description;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setErrorMessage(?string $errorMessage): self
    {
        $this->errorMessage = $errorMessage;
        return $this;
    }

    public function getErrorMessage(): ?string
    {
        return $this->errorMessage;
    }

    public function setCreateTimestamp(string $createTimestamp): self
    {
        $this->createTimestamp = $createTimestamp;
        return $this;
    }

    public function getCreateTimestamp(): string
    {
        return $this->createTimestamp;
    }

    public function setLinks(Link ...$links): self
    {
        $this->links = $links;
        return $this;
    }

    public function getLinks(): array
    {
        return $this->links;
    }
}
