<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V5\ReturnRequest\HandlingResult;

/**
 * @method static ReturnRequest fromArray(array $data)
 */
final class ReturnRequest extends Model
{
    /** @var HandlingResult */
    protected $handlingResult;

    /** @var int */
    protected $quantityReturned = 0;

    public function setHandlingResult(?HandlingResult $handlingResult): self
    {
        $this->handlingResult = $handlingResult;
        return $this;
    }

    public function getHandlingResult(): ?HandlingResult
    {
        return $this->handlingResult;
    }

    public function setQuantityReturned(int $quantityReturned): self
    {
        $this->quantityReturned = $quantityReturned;
        return $this;
    }

    public function getQuantityReturned(): int
    {
        return $this->quantityReturned;
    }
}
