<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static ShipmentFulfilment fromArray(array $data)
 */
final class ShipmentFulfilment extends Model
{
    /**
     * Specifies whether this shipment has been fulfilled by the retailer
     * (FBR) or fulfilled by bol.com (FBB). Defaults to FBR.
     * @var string
     */
    protected $method;

    /**
     * The party that manages the distribution, either bol.com or the
     * retailer itself.
     * @var string
     */
    protected $distributionParty;

    /**
     * The ultimate delivery date at which this order must be delivered at
     * the customer's shipping address. This field is empty in case the
     * exactDeliveryDate is filled.
     * @var string
     */
    protected $latestDeliveryDate;

    public function setMethod(?string $method): self
    {
        $this->method = $method;
        return $this;
    }

    public function getMethod(): ?string
    {
        return $this->method;
    }

    public function setDistributionParty(?string $distributionParty): self
    {
        $this->distributionParty = $distributionParty;
        return $this;
    }

    public function getDistributionParty(): ?string
    {
        return $this->distributionParty;
    }

    public function setLatestDeliveryDate(?string $latestDeliveryDate): self
    {
        $this->latestDeliveryDate = $latestDeliveryDate;
        return $this;
    }

    public function getLatestDeliveryDate(): ?string
    {
        return $this->latestDeliveryDate;
    }
}
