<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static TotalPeriod fromArray(array $data)
 */
final class TotalPeriod extends Model
{
    protected $period;

    /**
     * The number of customer visits on the search page.
     * @var int
     */
    protected $total;

    /** @var SearchTermsCountry[] */
    protected $countries;

    public function setPeriod($period): self
    {
        $this->period = $period;
        return $this;
    }

    public function getPeriod()
    {
        return $this->period;
    }

    public function setTotal(int $total): self
    {
        $this->total = $total;
        return $this;
    }

    public function getTotal(): int
    {
        return $this->total;
    }

    public function setCountries(SearchTermsCountry ...$countries): self
    {
        $this->countries = $countries;
        return $this;
    }

    public function getCountries(): array
    {
        return $this->countries;
    }
}
