<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Endpoints\V5;

use Inktweb\Bolcom\RetailerApi\Contracts\Endpoint;
use Inktweb\Bolcom\RetailerApi\Enums\V5\Shipments\FulfilmentMethod as FulfilmentMethodV5;
use Inktweb\Bolcom\RetailerApi\Models\V5\Problem;
use Inktweb\Bolcom\RetailerApi\Models\V5\Shipment;
use Inktweb\Bolcom\RetailerApi\Models\V5\ShipmentsResponse;

final class Shipments extends Endpoint
{
    /**
     * Get shipment list.
     *
     * A paginated list to retrieve all your shipments up to 3 months old.
     * The shipments will be sorted by date in descending order.
     */
    public function getShipments(
        ?int $page = null,
        ?FulfilmentMethodV5 $fulfilmentMethod = null,
        ?string $orderId = null
    ): ShipmentsResponse {
        return ShipmentsResponse::fromArray(
            $this->request(
                'get',
                'shipments',
                [],
                [
                'page' => $page,
                'fulfilment-method' => $fulfilmentMethod,
                'order-id' => $orderId,
                ],
                null,
                [
                'application/vnd.retailer.v5+json',
                ],
                [
                'application/vnd.retailer.v5+json',
                ],
                [
                400 => Problem::class,
                ]
            )
        );
    }

    /**
     * Get a shipment by shipment id.
     *
     * Retrieve a single shipment by its corresponding id.
     */
    public function getShipment(string $shipmentId): Shipment
    {
        return Shipment::fromArray(
            $this->request(
                'get',
                'shipments/{shipment-id}',
                [
                'shipment-id' => $shipmentId,
                ],
                [],
                null,
                [
                'application/vnd.retailer.v5+json',
                ],
                [
                'application/vnd.retailer.v5+json',
                ],
                [
                404 => Problem::class,
                ]
            )
        );
    }
}
