<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static Category fromArray(array $data)
 */
final class Category extends Model
{
    /** The id of the parent category which the product belongs to. */
    protected string $categoryId = '';

    /** The name of the parent category which the product belongs to. */
    protected string $categoryName = '';

    /**
     * The subcategories which the product belongs to.
     * @var SubCategory[]
     */
    protected ?array $subcategories = [];

    public function setCategoryId(string $categoryId): self
    {
        $this->categoryId = $categoryId;
        return $this;
    }

    public function getCategoryId(): string
    {
        return $this->categoryId;
    }

    public function setCategoryName(string $categoryName): self
    {
        $this->categoryName = $categoryName;
        return $this;
    }

    public function getCategoryName(): string
    {
        return $this->categoryName;
    }

    public function setSubcategories(?SubCategory ...$subcategories): self
    {
        $this->subcategories = $subcategories;
        return $this;
    }

    public function getSubcategories(): ?array
    {
        return $this->subcategories;
    }
}
