<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * Order items for which the delivery options are requested.
 * @method static DeliveryOptionsRequestOrderItem fromArray(array $data)
 */
final class DeliveryOptionsRequestOrderItem extends Model
{
    /** The id for the order item (1 order can have multiple order items). */
    protected string $orderItemId = '';

    /**
     * The quantity of the order item for which the shipping label creation
     * is requested for. If omitted, will be interpreted as the full quantity
     * that is still open for this order item.
     */
    protected ?int $quantity = 0;

    public function setOrderItemId(string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): string
    {
        return $this->orderItemId;
    }

    public function setQuantity(?int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->quantity;
    }
}
