<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * The list of range filters that is associated with the given search
 * term or category.
 * @method static FilterRanges fromArray(array $data)
 */
final class FilterRanges extends Model
{
    /** The id of the range filter product can be found under. */
    protected string $rangeId = '';

    /** The name of the range filter product can be found under. */
    protected string $rangeName = '';

    /** The minimum value for the range that can be used to filter results. */
    protected float $min = 0;

    /** The maximum value for the range that can be used to filter results. */
    protected float $max = 0;

    /** The unit that applies to the min and max range values. */
    protected string $unit = '';

    public function setRangeId(string $rangeId): self
    {
        $this->rangeId = $rangeId;
        return $this;
    }

    public function getRangeId(): string
    {
        return $this->rangeId;
    }

    public function setRangeName(string $rangeName): self
    {
        $this->rangeName = $rangeName;
        return $this;
    }

    public function getRangeName(): string
    {
        return $this->rangeName;
    }

    public function setMin(float $min): self
    {
        $this->min = $min;
        return $this;
    }

    public function getMin(): float
    {
        return $this->min;
    }

    public function setMax(float $max): self
    {
        $this->max = $max;
        return $this;
    }

    public function getMax(): float
    {
        return $this->max;
    }

    public function setUnit(string $unit): self
    {
        $this->unit = $unit;
        return $this;
    }

    public function getUnit(): string
    {
        return $this->unit;
    }
}
