<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V10\Retailer\ProductAssets\Usage;

/**
 * @method static ProductAssets fromArray(array $data)
 */
final class ProductAssets extends Model
{
    /** Type of the asset being used for. */
    protected Usage $usage;

    /** The intended order of the product images. */
    protected int $order = 0;

    /** @var ProductAssetsVariants[] */
    protected array $variants = [];

    public function setUsage(Usage $usage): self
    {
        $this->usage = $usage;
        return $this;
    }

    public function getUsage(): Usage
    {
        return $this->usage;
    }

    public function setOrder(int $order): self
    {
        $this->order = $order;
        return $this;
    }

    public function getOrder(): int
    {
        return $this->order;
    }

    public function setVariants(ProductAssetsVariants ...$variants): self
    {
        $this->variants = $variants;
        return $this;
    }

    public function getVariants(): array
    {
        return $this->variants;
    }
}
