<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * An order item.
 * @method static ReducedOrderItem fromArray(array $data)
 */
final class ReducedOrderItem extends Model
{
    /**
     * The id for the order item. One order can have multiple order items,
     * but the list can only take one item.
     */
    protected string $orderItemId = '';

    /** The EAN number associated with this product. */
    protected string $ean = '';

    /**
     * The fulfilment method. Fulfilled by the retailer (FBR) or fulfilled by
     * bol.com (FBB).
     */
    protected string $fulfilmentMethod = '';

    /**
     * To filter on order status. You can filter on either all orders
     * independent from their status, open orders (excluding shipped and
     * cancelled orders), and shipped orders.
     */
    protected string $fulfilmentStatus = '';

    /** Amount of ordered products for this order item id. */
    protected int $quantity = 0;

    /** Amount of shipped products for this order item id. */
    protected int $quantityShipped = 0;

    /** Amount of cancelled products for this order item id. */
    protected int $quantityCancelled = 0;

    /**
     * Indicates whether the order was cancelled on request of the customer
     * before the retailer has shipped it.
     */
    protected bool $cancellationRequest = false;

    /**
     * The date and time in ISO 8601 format when the orderItem was last
     * changed.
     */
    protected string $latestChangedDateTime = '';

    public function setOrderItemId(string $orderItemId): self
    {
        $this->orderItemId = $orderItemId;
        return $this;
    }

    public function getOrderItemId(): string
    {
        return $this->orderItemId;
    }

    public function setEan(string $ean): self
    {
        $this->ean = $ean;
        return $this;
    }

    public function getEan(): string
    {
        return $this->ean;
    }

    public function setFulfilmentMethod(string $fulfilmentMethod): self
    {
        $this->fulfilmentMethod = $fulfilmentMethod;
        return $this;
    }

    public function getFulfilmentMethod(): string
    {
        return $this->fulfilmentMethod;
    }

    public function setFulfilmentStatus(string $fulfilmentStatus): self
    {
        $this->fulfilmentStatus = $fulfilmentStatus;
        return $this;
    }

    public function getFulfilmentStatus(): string
    {
        return $this->fulfilmentStatus;
    }

    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;
        return $this;
    }

    public function getQuantity(): int
    {
        return $this->quantity;
    }

    public function setQuantityShipped(int $quantityShipped): self
    {
        $this->quantityShipped = $quantityShipped;
        return $this;
    }

    public function getQuantityShipped(): int
    {
        return $this->quantityShipped;
    }

    public function setQuantityCancelled(int $quantityCancelled): self
    {
        $this->quantityCancelled = $quantityCancelled;
        return $this;
    }

    public function getQuantityCancelled(): int
    {
        return $this->quantityCancelled;
    }

    public function setCancellationRequest(bool $cancellationRequest): self
    {
        $this->cancellationRequest = $cancellationRequest;
        return $this;
    }

    public function getCancellationRequest(): bool
    {
        return $this->cancellationRequest;
    }

    public function setLatestChangedDateTime(string $latestChangedDateTime): self
    {
        $this->latestChangedDateTime = $latestChangedDateTime;
        return $this;
    }

    public function getLatestChangedDateTime(): string
    {
        return $this->latestChangedDateTime;
    }
}
