<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V10\Retailer\RetailerInformationResponse\RatingMethod;

/**
 * @method static RetailerInformationResponse fromArray(array $data)
 */
final class RetailerInformationResponse extends Model
{
    /** The Id of the retailer which information belongs to. */
    protected string $retailerId = '';

    /** The name of the retailer visible on bol.com */
    protected string $displayName = '';

    /**
     * A date representing the registration date for the retailer within
     * bol.com
     */
    protected string $registrationDate = '';

    /** Indication of retailer's being the top seller. */
    protected ?bool $topRetailer = false;

    /**
     * An identifier that identifies if the rating is calculated over the
     * past three months or on all reviews for the retailer.
     */
    protected ?RatingMethod $ratingMethod = null;
    protected ?RetailerRating $retailerRating = null;
    protected ?RetailerReview $retailerReview = null;

    public function setRetailerId(string $retailerId): self
    {
        $this->retailerId = $retailerId;
        return $this;
    }

    public function getRetailerId(): string
    {
        return $this->retailerId;
    }

    public function setDisplayName(string $displayName): self
    {
        $this->displayName = $displayName;
        return $this;
    }

    public function getDisplayName(): string
    {
        return $this->displayName;
    }

    public function setRegistrationDate(string $registrationDate): self
    {
        $this->registrationDate = $registrationDate;
        return $this;
    }

    public function getRegistrationDate(): string
    {
        return $this->registrationDate;
    }

    public function setTopRetailer(?bool $topRetailer): self
    {
        $this->topRetailer = $topRetailer;
        return $this;
    }

    public function getTopRetailer(): ?bool
    {
        return $this->topRetailer;
    }

    public function setRatingMethod(?RatingMethod $ratingMethod): self
    {
        $this->ratingMethod = $ratingMethod;
        return $this;
    }

    public function getRatingMethod(): ?RatingMethod
    {
        return $this->ratingMethod;
    }

    public function setRetailerRating(?RetailerRating $retailerRating): self
    {
        $this->retailerRating = $retailerRating;
        return $this;
    }

    public function getRetailerRating(): ?RetailerRating
    {
        return $this->retailerRating;
    }

    public function setRetailerReview(?RetailerReview $retailerReview): self
    {
        $this->retailerReview = $retailerReview;
        return $this;
    }

    public function getRetailerReview(): ?RetailerReview
    {
        return $this->retailerReview;
    }
}
