<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V10\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static SearchTerms fromArray(array $data)
 */
final class SearchTerms extends Model
{
    protected ?SearchTerm $searchTerms = null;

    public function setSearchTerms(?SearchTerm $searchTerms): self
    {
        $this->searchTerms = $searchTerms;
        return $this;
    }

    public function getSearchTerms(): ?SearchTerm
    {
        return $this->searchTerms;
    }
}
