<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer;

use GuzzleHttp\Exception\GuzzleException;
use Inktweb\Bolcom\RetailerApi\Contracts\Endpoint;
use Inktweb\Bolcom\RetailerApi\Exceptions\ApiException;
use Inktweb\Bolcom\RetailerApi\Exceptions\Enum\UnknownCollectionFormatException;
use Inktweb\Bolcom\RetailerApi\Exceptions\UnexpectedResponseContentTypeException;
use Inktweb\Bolcom\RetailerApi\Models\V9\Retailer\Problem;
use Inktweb\Bolcom\RetailerApi\Models\V9\Retailer\RetailerInformationResponse;

final class Retailers extends Endpoint
{
    /**
     * Get retailer information by retailer id.
     *
     * Gets retailer information of a single retailer.
     *
     * @throws ApiException
     * @throws GuzzleException
     * @throws UnexpectedResponseContentTypeException
     * @throws UnknownCollectionFormatException
     */
    public function getRetailerInformation(string $retailerId): RetailerInformationResponse
    {
        return RetailerInformationResponse::fromArray(
            $this->request(
                'get',
                'retailers/{retailer-id}',
                [
                    'retailer-id' => $retailerId,
                ],
                [],
                null,
                [
                    'application/vnd.retailer.v9+json',
                ],
                [
                    'application/vnd.retailer.v9+json',
                ],
                [
                    400 => Problem::class,
                    404 => Problem::class,
                ]
            )->getBody()->getJson()
        );
    }
}
