<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V6\PickupAppointment;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class CancellationReason extends Enum
{
    protected const MAX_ITEMS = 1;
    public const UNKNOWN_ADDRESS = 'UNKNOWN_ADDRESS';
    public const NOT_READY = 'NOT_READY';
    public const NO_LABEL = 'NO_LABEL';
    public const WRONG_PACKAGE = 'WRONG_PACKAGE';
    public const NOT_AT_HOME = 'NOT_AT_HOME';
    public const OTHER_REASON = 'OTHER_REASON';
    public const REQUEST_FROM_RETAILER = 'REQUEST_FROM_RETAILER';

    protected $allowedValues = [
        'UNKNOWN_ADDRESS',
        'NOT_READY',
        'NO_LABEL',
        'WRONG_PACKAGE',
        'NOT_AT_HOME',
        'OTHER_REASON',
        'REQUEST_FROM_RETAILER',
    ];

    public static function unknownAddress(): self
    {
        return (new static())->set(static::UNKNOWN_ADDRESS);
    }

    public function isUnknownAddress(): bool
    {
        return $this->is(static::UNKNOWN_ADDRESS);
    }

    public static function notReady(): self
    {
        return (new static())->set(static::NOT_READY);
    }

    public function isNotReady(): bool
    {
        return $this->is(static::NOT_READY);
    }

    public static function noLabel(): self
    {
        return (new static())->set(static::NO_LABEL);
    }

    public function isNoLabel(): bool
    {
        return $this->is(static::NO_LABEL);
    }

    public static function wrongPackage(): self
    {
        return (new static())->set(static::WRONG_PACKAGE);
    }

    public function isWrongPackage(): bool
    {
        return $this->is(static::WRONG_PACKAGE);
    }

    public static function notAtHome(): self
    {
        return (new static())->set(static::NOT_AT_HOME);
    }

    public function isNotAtHome(): bool
    {
        return $this->is(static::NOT_AT_HOME);
    }

    public static function otherReason(): self
    {
        return (new static())->set(static::OTHER_REASON);
    }

    public function isOtherReason(): bool
    {
        return $this->is(static::OTHER_REASON);
    }

    public static function requestFromRetailer(): self
    {
        return (new static())->set(static::REQUEST_FROM_RETAILER);
    }

    public function isRequestFromRetailer(): bool
    {
        return $this->is(static::REQUEST_FROM_RETAILER);
    }
}
