<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Endpoints\V7;

use Inktweb\Bolcom\RetailerApi\Contracts\Endpoint;
use Inktweb\Bolcom\RetailerApi\Models\V7\CreateProductContentSingleRequest;
use Inktweb\Bolcom\RetailerApi\Models\V7\Problem;
use Inktweb\Bolcom\RetailerApi\Models\V7\ProcessStatus;
use Inktweb\Bolcom\RetailerApi\Models\V7\UploadReportResponse;

final class ProductContent extends Endpoint
{
    /**
     * Create content for a product.
     *
     * Create content for an existing product.
     */
    public function postProductContent(CreateProductContentSingleRequest $body): ProcessStatus
    {
        return ProcessStatus::fromArray(
            $this->request(
                'post',
                'content/products',
                [],
                [],
                $body,
                [
                'application/vnd.retailer.v7+json',
                ],
                [
                'application/vnd.retailer.v7+json',
                ],
                [
                400 => Problem::class,
                ]
            )->getBody()->getJson()
        );
    }

    /**
     * Get an upload report by upload id.
     *
     * Gets the upload report of the product content submitted by upload id.
     */
    public function getUploadReport(string $uploadId): UploadReportResponse
    {
        return UploadReportResponse::fromArray(
            $this->request(
                'get',
                'content/upload-report/{upload-id}',
                [
                'upload-id' => $uploadId,
                ],
                [],
                null,
                [
                'application/vnd.retailer.v7+json',
                ],
                [
                'application/vnd.retailer.v7+json',
                ],
                [
                404 => Problem::class,
                ]
            )->getBody()->getJson()
        );
    }
}
