<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Endpoints\V10\Retailer\Orders;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class Status extends Enum
{
    public const OPEN = 'OPEN';
    public const SHIPPED = 'SHIPPED';
    public const ALL = 'ALL';

    protected array $allowedValues = ['OPEN', 'SHIPPED', 'ALL'];

    public static function open(): self
    {
        return (new static())->set(static::OPEN);
    }

    public function isOpen(): bool
    {
        return $this->is(static::OPEN);
    }

    public static function shipped(): self
    {
        return (new static())->set(static::SHIPPED);
    }

    public function isShipped(): bool
    {
        return $this->is(static::SHIPPED);
    }

    public static function all(): self
    {
        return (new static())->set(static::ALL);
    }

    public function isAll(): bool
    {
        return $this->is(static::ALL);
    }
}
