<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V7\UpdateReplenishmentRequest;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class State extends Enum
{
    protected const MAX_ITEMS = 1;
    public const CANCELLED = 'CANCELLED';

    protected $allowedValues = ['CANCELLED'];

    public static function cancelled(): self
    {
        return (new static())->set(static::CANCELLED);
    }

    public function isCancelled(): bool
    {
        return $this->is(static::CANCELLED);
    }
}
