<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Apis
 */

namespace Inktweb\Bolcom\RetailerApi\Apis\V9;

use Inktweb\Bolcom\RetailerApi\Contracts\Api;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Commissions;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Insights;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Inventory;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Invoices;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Offers;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Orders;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\ProductContent;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Products;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Promotions;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Replenishments;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Retailers;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Returns;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Shipments;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\ShippingLabels;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Subscriptions;
use Inktweb\Bolcom\RetailerApi\Endpoints\V9\Retailer\Transports;

final class Retailer extends Api
{
    protected Commissions $commissions;
    protected ProductContent $productContent;
    protected Insights $insights;
    protected Inventory $inventory;
    protected Invoices $invoices;
    protected Offers $offers;
    protected Orders $orders;
    protected Products $products;
    protected Promotions $promotions;
    protected Replenishments $replenishments;
    protected Retailers $retailers;
    protected Returns $returns;
    protected Shipments $shipments;
    protected ShippingLabels $shippingLabels;
    protected Subscriptions $subscriptions;
    protected Transports $transports;

    public function commissions(): Commissions
    {
        return $this->commissions
            ?? $this->commissions = new Commissions($this->client);
    }

    public function productContent(): ProductContent
    {
        return $this->productContent
            ?? $this->productContent = new ProductContent($this->client);
    }

    public function insights(): Insights
    {
        return $this->insights
            ?? $this->insights = new Insights($this->client);
    }

    public function inventory(): Inventory
    {
        return $this->inventory
            ?? $this->inventory = new Inventory($this->client);
    }

    public function invoices(): Invoices
    {
        return $this->invoices
            ?? $this->invoices = new Invoices($this->client);
    }

    public function offers(): Offers
    {
        return $this->offers
            ?? $this->offers = new Offers($this->client);
    }

    public function orders(): Orders
    {
        return $this->orders
            ?? $this->orders = new Orders($this->client);
    }

    public function products(): Products
    {
        return $this->products
            ?? $this->products = new Products($this->client);
    }

    public function promotions(): Promotions
    {
        return $this->promotions
            ?? $this->promotions = new Promotions($this->client);
    }

    public function replenishments(): Replenishments
    {
        return $this->replenishments
            ?? $this->replenishments = new Replenishments($this->client);
    }

    public function retailers(): Retailers
    {
        return $this->retailers
            ?? $this->retailers = new Retailers($this->client);
    }

    public function returns(): Returns
    {
        return $this->returns
            ?? $this->returns = new Returns($this->client);
    }

    public function shipments(): Shipments
    {
        return $this->shipments
            ?? $this->shipments = new Shipments($this->client);
    }

    public function shippingLabels(): ShippingLabels
    {
        return $this->shippingLabels
            ?? $this->shippingLabels = new ShippingLabels($this->client);
    }

    public function subscriptions(): Subscriptions
    {
        return $this->subscriptions
            ?? $this->subscriptions = new Subscriptions($this->client);
    }

    public function transports(): Transports
    {
        return $this->transports
            ?? $this->transports = new Transports($this->client);
    }
}
