<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * Container for multiple campaigns.
 * @method static CampaignsResponse fromArray(array $data)
 */
final class CampaignsResponse extends Model
{
    /** @var SingleCampaignResponse[] */
    protected array $campaigns = [];

    public function setCampaigns(SingleCampaignResponse ...$campaigns): self
    {
        $this->campaigns = $campaigns;
        return $this;
    }

    public function getCampaigns(): array
    {
        return $this->campaigns;
    }
}
