<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Endpoints
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Endpoints\V10\Retailer\Products;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class Usage extends Enum
{
    public const PRIMARY = 'PRIMARY';
    public const ADDITIONAL = 'ADDITIONAL';
    public const IMAGE = 'IMAGE';

    protected array $allowedValues = ['PRIMARY', 'ADDITIONAL', 'IMAGE'];

    public static function primary(): self
    {
        return (new static())->set(static::PRIMARY);
    }

    public function isPrimary(): bool
    {
        return $this->is(static::PRIMARY);
    }

    public static function additional(): self
    {
        return (new static())->set(static::ADDITIONAL);
    }

    public function isAdditional(): bool
    {
        return $this->is(static::ADDITIONAL);
    }

    public static function image(): self
    {
        return (new static())->set(static::IMAGE);
    }

    public function isImage(): bool
    {
        return $this->is(static::IMAGE);
    }
}
