<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V6\ProductLabelsRequest;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class LabelFormat extends Enum
{
    protected const MAX_ITEMS = 1;
    public const AVERY_J8159 = 'AVERY_J8159';
    public const AVERY_J8160 = 'AVERY_J8160';
    public const AVERY_3474 = 'AVERY_3474';
    public const DYMO_99012 = 'DYMO_99012';
    public const BROTHER_DK11208D = 'BROTHER_DK11208D';
    public const ZEBRA_Z_PERFORM_1000T = 'ZEBRA_Z_PERFORM_1000T';

    protected $allowedValues = [
        'AVERY_J8159',
        'AVERY_J8160',
        'AVERY_3474',
        'DYMO_99012',
        'BROTHER_DK11208D',
        'ZEBRA_Z_PERFORM_1000T',
    ];

    public static function averyJ8159(): self
    {
        return (new static())->set(static::AVERY_J8159);
    }

    public function isAveryJ8159(): bool
    {
        return $this->is(static::AVERY_J8159);
    }

    public static function averyJ8160(): self
    {
        return (new static())->set(static::AVERY_J8160);
    }

    public function isAveryJ8160(): bool
    {
        return $this->is(static::AVERY_J8160);
    }

    public static function avery3474(): self
    {
        return (new static())->set(static::AVERY_3474);
    }

    public function isAvery3474(): bool
    {
        return $this->is(static::AVERY_3474);
    }

    public static function dymo99012(): self
    {
        return (new static())->set(static::DYMO_99012);
    }

    public function isDymo99012(): bool
    {
        return $this->is(static::DYMO_99012);
    }

    public static function brotherDk11208d(): self
    {
        return (new static())->set(static::BROTHER_DK11208D);
    }

    public function isBrotherDk11208d(): bool
    {
        return $this->is(static::BROTHER_DK11208D);
    }

    public static function zebraZPerform1000t(): self
    {
        return (new static())->set(static::ZEBRA_Z_PERFORM_1000T);
    }

    public function isZebraZPerform1000t(): bool
    {
        return $this->is(static::ZEBRA_Z_PERFORM_1000T);
    }
}
