<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Advertiser\CreateNegativeKeywordRequest\MatchType;

/**
 * @method static CreateNegativeKeywordRequest fromArray(array $data)
 */
final class CreateNegativeKeywordRequest extends Model
{
    /** The identifier of the parent ad group. */
    protected string $adGroupId = '';

    /**
     * The text or phrase used in the negative keyword that caused the ad not
     * to be displayed to the user.
     */
    protected string $keywordText = '';

    /** The match type that relates the negative keyword and the search term. */
    protected MatchType $matchType;

    public function setAdGroupId(string $adGroupId): self
    {
        $this->adGroupId = $adGroupId;
        return $this;
    }

    public function getAdGroupId(): string
    {
        return $this->adGroupId;
    }

    public function setKeywordText(string $keywordText): self
    {
        $this->keywordText = $keywordText;
        return $this;
    }

    public function getKeywordText(): string
    {
        return $this->keywordText;
    }

    public function setMatchType(MatchType $matchType): self
    {
        $this->matchType = $matchType;
        return $this;
    }

    public function getMatchType(): MatchType
    {
        return $this->matchType;
    }
}
