<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Advertiser\CreateBiddingModel\Strategy;

/**
 * @method static CreateBiddingModel fromArray(array $data)
 */
final class CreateBiddingModel extends Model
{
    /** The type of strategy you will use for bidding on advertisements. */
    protected Strategy $strategy;

    /**
     * Only required when the bidding strategy is set to AUTO. When provided,
     * the bidding strategy will attempt to reach this ACoS. The format is a
     * number without decimals that represents a percentage.
     */
    protected ?int $automaticBidDesiredAcosPercentage = 0;

    /**
     * The default bid price. The price should always have two decimals
     * precision.
     */
    protected ?float $defaultBid = 0;

    public function setStrategy(Strategy $strategy): self
    {
        $this->strategy = $strategy;
        return $this;
    }

    public function getStrategy(): Strategy
    {
        return $this->strategy;
    }

    public function setAutomaticBidDesiredAcosPercentage(?int $automaticBidDesiredAcosPercentage): self
    {
        $this->automaticBidDesiredAcosPercentage = $automaticBidDesiredAcosPercentage;
        return $this;
    }

    public function getAutomaticBidDesiredAcosPercentage(): ?int
    {
        return $this->automaticBidDesiredAcosPercentage;
    }

    public function setDefaultBid(?float $defaultBid): self
    {
        $this->defaultBid = $defaultBid;
        return $this;
    }

    public function getDefaultBid(): ?float
    {
        return $this->defaultBid;
    }
}
