<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Advertiser;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Advertiser\UpdateAdGroupRequest\State;

/**
 * @method static UpdateAdGroupRequest fromArray(array $data)
 */
final class UpdateAdGroupRequest extends Model
{
    /** The name of the ad group. */
    protected string $name = '';

    /** The state of the ad group. */
    protected State $state;

    /**
     * The default bid price. The price should always have two decimals
     * precision.
     */
    protected float $defaultBid = 0;

    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setState(?State $state): self
    {
        $this->state = $state;
        return $this;
    }

    public function getState(): ?State
    {
        return $this->state;
    }

    public function setDefaultBid(?float $defaultBid): self
    {
        $this->defaultBid = $defaultBid;
        return $this;
    }

    public function getDefaultBid(): ?float
    {
        return $this->defaultBid;
    }
}
