<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V5\Condition;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class Category extends Enum
{
    public const NEW = 'NEW';
    public const SECONDHAND = 'SECONDHAND';

    protected $allowedValues = ['NEW', 'SECONDHAND'];

    public static function new(): self
    {
        return (new static())->set(static::NEW);
    }

    public static function secondhand(): self
    {
        return (new static())->set(static::SECONDHAND);
    }
}
