<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Enums\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Enums\Models\V10\Retailer\SubscriptionResponse;

use Inktweb\Bolcom\RetailerApi\Contracts\Enum;

class Resources extends Enum
{
    public const TEST = 'TEST';
    public const PROCESS_STATUS = 'PROCESS_STATUS';
    public const SHIPMENT = 'SHIPMENT';
    public const OFFER = 'OFFER';
    public const PRICE_STAR_BOUNDARY = 'PRICE_STAR_BOUNDARY';
    public const COMPETING_OFFER = 'COMPETING_OFFER';

    protected array $allowedValues = [
        'TEST',
        'PROCESS_STATUS',
        'SHIPMENT',
        'OFFER',
        'PRICE_STAR_BOUNDARY',
        'COMPETING_OFFER',
    ];

    public static function test(): self
    {
        return (new static())->set(static::TEST);
    }

    public function isTest(): bool
    {
        return $this->is(static::TEST);
    }

    public static function processStatus(): self
    {
        return (new static())->set(static::PROCESS_STATUS);
    }

    public function isProcessStatus(): bool
    {
        return $this->is(static::PROCESS_STATUS);
    }

    public static function shipment(): self
    {
        return (new static())->set(static::SHIPMENT);
    }

    public function isShipment(): bool
    {
        return $this->is(static::SHIPMENT);
    }

    public static function offer(): self
    {
        return (new static())->set(static::OFFER);
    }

    public function isOffer(): bool
    {
        return $this->is(static::OFFER);
    }

    public static function priceStarBoundary(): self
    {
        return (new static())->set(static::PRICE_STAR_BOUNDARY);
    }

    public function isPriceStarBoundary(): bool
    {
        return $this->is(static::PRICE_STAR_BOUNDARY);
    }

    public static function competingOffer(): self
    {
        return (new static())->set(static::COMPETING_OFFER);
    }

    public function isCompetingOffer(): bool
    {
        return $this->is(static::COMPETING_OFFER);
    }
}
