<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static AudioTracks fromArray(array $data)
 */
final class AudioTracks extends Model
{
    /** The disc number within an album the audio track is stored on. */
    protected ?string $discNumber = '';

    /** The track number on the album. */
    protected ?string $trackNumber = '';

    /** The disc side on which the audio track is stored on. */
    protected ?string $discSide = '';

    /** The title of the audio track. */
    protected ?string $title = '';

    /** The name of the artist(s) performing the audio track. */
    protected ?string $artistName = '';

    /** The play time of the audio track. */
    protected ?string $playTime = '';

    /**
     * The URL on which an audio clip of the audio track has been made
     * available.
     */
    protected ?string $clipUrl = '';

    /** The format in which the audio clip is available. */
    protected ?string $clipType = '';

    public function setDiscNumber(?string $discNumber): self
    {
        $this->discNumber = $discNumber;
        return $this;
    }

    public function getDiscNumber(): ?string
    {
        return $this->discNumber;
    }

    public function setTrackNumber(?string $trackNumber): self
    {
        $this->trackNumber = $trackNumber;
        return $this;
    }

    public function getTrackNumber(): ?string
    {
        return $this->trackNumber;
    }

    public function setDiscSide(?string $discSide): self
    {
        $this->discSide = $discSide;
        return $this;
    }

    public function getDiscSide(): ?string
    {
        return $this->discSide;
    }

    public function setTitle(?string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setArtistName(?string $artistName): self
    {
        $this->artistName = $artistName;
        return $this;
    }

    public function getArtistName(): ?string
    {
        return $this->artistName;
    }

    public function setPlayTime(?string $playTime): self
    {
        $this->playTime = $playTime;
        return $this;
    }

    public function getPlayTime(): ?string
    {
        return $this->playTime;
    }

    public function setClipUrl(?string $clipUrl): self
    {
        $this->clipUrl = $clipUrl;
        return $this;
    }

    public function getClipUrl(): ?string
    {
        return $this->clipUrl;
    }

    public function setClipType(?string $clipType): self
    {
        $this->clipType = $clipType;
        return $this;
    }

    public function getClipType(): ?string
    {
        return $this->clipType;
    }
}
