<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static Inventory fromArray(array $data)
 */
final class Inventory extends Model
{
    /** The EAN number associated with this product. */
    protected string $ean = '';

    /** The BSKU number associated with this product. */
    protected string $bsku = '';

    /** The stock that is not available for sale anymore. */
    protected int $gradedStock = 0;

    /** The stock that is available for sale. */
    protected int $regularStock = 0;

    /** The product title. */
    protected string $title = '';

    public function setEan(string $ean): self
    {
        $this->ean = $ean;
        return $this;
    }

    public function getEan(): string
    {
        return $this->ean;
    }

    public function setBsku(string $bsku): self
    {
        $this->bsku = $bsku;
        return $this;
    }

    public function getBsku(): string
    {
        return $this->bsku;
    }

    public function setGradedStock(int $gradedStock): self
    {
        $this->gradedStock = $gradedStock;
        return $this;
    }

    public function getGradedStock(): int
    {
        return $this->gradedStock;
    }

    public function setRegularStock(int $regularStock): self
    {
        $this->regularStock = $regularStock;
        return $this;
    }

    public function getRegularStock(): int
    {
        return $this->regularStock;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;
        return $this;
    }

    public function getTitle(): string
    {
        return $this->title;
    }
}
