<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static InventoryResponse fromArray(array $data)
 */
final class InventoryResponse extends Model
{
    /** @var Inventory[] */
    protected array $inventory = [];

    public function setInventory(Inventory ...$inventory): self
    {
        $this->inventory = $inventory;
        return $this;
    }

    public function getInventory(): array
    {
        return $this->inventory;
    }
}
