<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static ProductIdsResponse fromArray(array $data)
 */
final class ProductIdsResponse extends Model
{
    /** Identifier of the product. This id is specific to bol.com webshop. */
    protected string $bolProductId = '';

    /** @var ProductIdsEan[] */
    protected array $eans = [];

    public function setBolProductId(string $bolProductId): self
    {
        $this->bolProductId = $bolProductId;
        return $this;
    }

    public function getBolProductId(): string
    {
        return $this->bolProductId;
    }

    public function setEans(ProductIdsEan ...$eans): self
    {
        $this->eans = $eans;
        return $this;
    }

    public function getEans(): array
    {
        return $this->eans;
    }
}
