<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static ProductDestinationWarehouse fromArray(array $data)
 */
final class ProductDestinationWarehouse extends Model
{
    protected ProductDestinationAddress $address;

    public function setAddress(ProductDestinationAddress $address): self
    {
        $this->address = $address;
        return $this;
    }

    public function getAddress(): ProductDestinationAddress
    {
        return $this->address;
    }
}
