<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static ProductRatingsResponse fromArray(array $data)
 */
final class ProductRatingsResponse extends Model
{
    /** @var ProductRatingsRating[] */
    protected array $ratings = [];

    public function setRatings(ProductRatingsRating ...$ratings): self
    {
        $this->ratings = $ratings;
        return $this;
    }

    public function getRatings(): array
    {
        return $this->ratings;
    }
}
