<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static RetailerRating fromArray(array $data)
 */
final class RetailerRating extends Model
{
    /** General rating of the retailer. */
    protected float $retailerRating = 0;

    /** Product rating of the retailer. */
    protected ?float $productInformationRating = 0;

    /** Delivery rating of the retailer. */
    protected ?float $deliveryTimeRating = 0;

    /** Shipping rating of the retailer. */
    protected ?float $shippingRating = 0;

    /** Service rating of the retailer. */
    protected ?float $serviceRating = 0;

    public function setRetailerRating(float $retailerRating): self
    {
        $this->retailerRating = $retailerRating;
        return $this;
    }

    public function getRetailerRating(): float
    {
        return $this->retailerRating;
    }

    public function setProductInformationRating(?float $productInformationRating): self
    {
        $this->productInformationRating = $productInformationRating;
        return $this;
    }

    public function getProductInformationRating(): ?float
    {
        return $this->productInformationRating;
    }

    public function setDeliveryTimeRating(?float $deliveryTimeRating): self
    {
        $this->deliveryTimeRating = $deliveryTimeRating;
        return $this;
    }

    public function getDeliveryTimeRating(): ?float
    {
        return $this->deliveryTimeRating;
    }

    public function setShippingRating(?float $shippingRating): self
    {
        $this->shippingRating = $shippingRating;
        return $this;
    }

    public function getShippingRating(): ?float
    {
        return $this->shippingRating;
    }

    public function setServiceRating(?float $serviceRating): self
    {
        $this->serviceRating = $serviceRating;
        return $this;
    }

    public function getServiceRating(): ?float
    {
        return $this->serviceRating;
    }
}
