<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static SearchTermsCountry fromArray(array $data)
 */
final class SearchTermsCountry extends Model
{
    /**
     * Countries in which this offer is currently on sale in the webshop in
     * ISO-3166-1 format.
     */
    protected string $countryCode = '';

    /** The number of customer visits on the search page. */
    protected int $value = 0;

    public function setCountryCode(string $countryCode): self
    {
        $this->countryCode = $countryCode;
        return $this;
    }

    public function getCountryCode(): string
    {
        return $this->countryCode;
    }

    public function setValue(int $value): self
    {
        $this->value = $value;
        return $this;
    }

    public function getValue(): int
    {
        return $this->value;
    }
}
