<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V9\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V9\Retailer\UploadReportResponse\Language;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V9\Retailer\UploadReportResponse\Status;

/**
 * Upload report.
 * @method static UploadReportResponse fromArray(array $data)
 */
final class UploadReportResponse extends Model
{
    /** The identifier of the upload report. */
    protected string $uploadId = '';

    /** The language in which content is submitted. */
    protected Language $language;

    /** The current status of the upload report. */
    protected Status $status;

    /** @var UploadReportAttribute[] */
    protected array $attributes = [];

    /** @var UploadReportAsset[] */
    protected ?array $assets = [];

    public function setUploadId(string $uploadId): self
    {
        $this->uploadId = $uploadId;
        return $this;
    }

    public function getUploadId(): string
    {
        return $this->uploadId;
    }

    public function setLanguage(Language $language): self
    {
        $this->language = $language;
        return $this;
    }

    public function getLanguage(): Language
    {
        return $this->language;
    }

    public function setStatus(Status $status): self
    {
        $this->status = $status;
        return $this;
    }

    public function getStatus(): Status
    {
        return $this->status;
    }

    public function setAttributes(UploadReportAttribute ...$attributes): self
    {
        $this->attributes = $attributes;
        return $this;
    }

    public function getAttributes(): array
    {
        return $this->attributes;
    }

    public function setAssets(?UploadReportAsset ...$assets): self
    {
        $this->assets = $assets;
        return $this;
    }

    public function getAssets(): ?array
    {
        return $this->assets;
    }
}
