<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;

/**
 * @method static Campaign fromArray(array $data)
 */
final class Campaign extends Model
{
    /** The name of the campaign under which the promotion had been created. */
    protected string $name = '';

    /** The starting date and time of the campaign. */
    protected string $startDateTime = '';

    /** The ending date and time of the campaign. */
    protected string $endDateTime = '';

    public function setName(string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setStartDateTime(string $startDateTime): self
    {
        $this->startDateTime = $startDateTime;
        return $this;
    }

    public function getStartDateTime(): string
    {
        return $this->startDateTime;
    }

    public function setEndDateTime(?string $endDateTime): self
    {
        $this->endDateTime = $endDateTime;
        return $this;
    }

    public function getEndDateTime(): ?string
    {
        return $this->endDateTime;
    }
}
