<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Retailer\Condition\Category;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Retailer\Condition\Name;

/**
 * @method static Condition fromArray(array $data)
 */
final class Condition extends Model
{
    /** The condition of the offered product. */
    protected Name $name;

    /**
     * The category of the condition. If not given NEW or SECONDHAND is
     * derived from NAME.
     */
    protected Category $category;

    /**
     * The description of the condition of the product. Only allowed if name
     * is not NEW and may not contain e-mail addresses.
     */
    protected string $comment = '';

    public function setName(Name $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): Name
    {
        return $this->name;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;
        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;
        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }
}
