<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Retailer\KeySet\Type;

/**
 * @method static KeySet fromArray(array $data)
 */
final class KeySet extends Model
{
    /**
     * Key identifier. Maps to the keyId value in the signature header of the
     * push request.
     */
    protected ?string $id = '';

    /** Key encryption type. */
    protected ?Type $type = null;

    /** The Base64 encoded public key to use when verifying the signature. */
    protected ?string $publicKey = '';

    public function setId(?string $id): self
    {
        $this->id = $id;
        return $this;
    }

    public function getId(): ?string
    {
        return $this->id;
    }

    public function setType(?Type $type): self
    {
        $this->type = $type;
        return $this;
    }

    public function getType(): ?Type
    {
        return $this->type;
    }

    public function setPublicKey(?string $publicKey): self
    {
        $this->publicKey = $publicKey;
        return $this;
    }

    public function getPublicKey(): ?string
    {
        return $this->publicKey;
    }
}
