<?php

/**
 * This file is auto-generated by
 * Inktweb\Bolcom\RetailerApi\Development\Generator\Models
 */

namespace Inktweb\Bolcom\RetailerApi\Models\V8\Retailer;

use Inktweb\Bolcom\RetailerApi\Contracts\Model;
use Inktweb\Bolcom\RetailerApi\Enums\Models\V8\Retailer\LoadCarrier\TransportState;

/**
 * @method static LoadCarrier fromArray(array $data)
 */
final class LoadCarrier extends Model
{
    /** The Serial Shipping Container Code (SSCC) for this load carrier. */
    protected string $sscc = '';

    /** The track and trace code for this load carrier. */
    protected string $transportLabelTrackAndTrace = '';

    /** The current state of the transport for this load carrier. */
    protected TransportState $transportState;

    /**
     * The date and time in ISO 8601 format when the latest update for this
     * transport was received.
     */
    protected string $transportStateUpdateDateTime = '';

    public function setSscc(?string $sscc): self
    {
        $this->sscc = $sscc;
        return $this;
    }

    public function getSscc(): ?string
    {
        return $this->sscc;
    }

    public function setTransportLabelTrackAndTrace(?string $transportLabelTrackAndTrace): self
    {
        $this->transportLabelTrackAndTrace = $transportLabelTrackAndTrace;
        return $this;
    }

    public function getTransportLabelTrackAndTrace(): ?string
    {
        return $this->transportLabelTrackAndTrace;
    }

    public function setTransportState(TransportState $transportState): self
    {
        $this->transportState = $transportState;
        return $this;
    }

    public function getTransportState(): TransportState
    {
        return $this->transportState;
    }

    public function setTransportStateUpdateDateTime(string $transportStateUpdateDateTime): self
    {
        $this->transportStateUpdateDateTime = $transportStateUpdateDateTime;
        return $this;
    }

    public function getTransportStateUpdateDateTime(): string
    {
        return $this->transportStateUpdateDateTime;
    }
}
